---
#- name: "Update systemd unit"
#  become: yes
#  hosts: web
#  tasks:
#    - name: "Provide latest unit file"
#      copy:
#        src: files/api.service
#        dest: /etc/systemd/system/api.service
#    - name: "Systemctl daemon reload"
#      command: systemctl daemon-reload
#- name: "Install docker"
#  become: yes
#  hosts: all
#  roles:
#    - role: geerlingguy.docker
#- name: Установка Docker и Docker Compose
#  hosts: all
#  become: true
#
#  tasks:
#    - name: Установка зависимостей для Docker Compose
#      apt:
#        name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
#        state: present
#
#    - name: Добавление официального репозитория Docker
#      apt_repository:
#        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
#        state: present
#
#    - name: Установка Docker
#      apt:
#        name: docker-ce
#        state: present
#
#    - name: Установка Docker Compose
#      shell: curl -L "https://github.com/docker/compose/releases/download/2.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose

#- name: "Install nginx"
#  become: yes
#  hosts: web
#  tasks:
#    - name: "Install nginx package"
#      apt:
#        name: nginx
#        state: present
#    - name: "Copy nginx config"
#      copy:
#        src: files/netflix.conf
#        dest: /etc/nginx/conf.d/
#    - name: "Reload nginx"
#      command: "systemctl restart nginx"

- name: "Install nginx"
  become: yes
  hosts: web
  tasks:
    - name: "Install nginx package"
      apt:
        name: nginx
        state: present
    - name: "Copy nginx config"
      copy:
        src: files/netflix.conf
        dest: /etc/nginx/conf.d/
    - name: "Reload nginx"
      command: "systemctl restart nginx"
